### ISSUE TITLE
ModuleNotFoundError on pip install

### ISSUE THREAD

**Issue by krokofant** [shuxin/apk-signature-verify#4]
```
Collecting apkverify
  Using cached https://files.pythonhosted.org/packages/5b/ae/2cee33c86c4cb5e81d732ad8f3f78ccff3106bc5b8c8969467f3c3541dd4/apkverify-0.1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3f/ts92xp0d3wn31g7_tgj6p_s00000gn/T/pip-install-ec0todpb/apkverify/setup.py", line 9, in <module>
        import apkverify
      File "/private/var/folders/3f/ts92xp0d3wn31g7_tgj6p_s00000gn/T/pip-install-ec0todpb/apkverify/apkverify/__init__.py", line 5, in <module>
        from .apkverify import ApkSignature
      File "/private/var/folders/3f/ts92xp0d3wn31g7_tgj6p_s00000gn/T/pip-install-ec0todpb/apkverify/apkverify/apkverify.py", line 25, in <module>
        from .sigverify import check_sig_pkcs7, check_sig_v2
      File "/private/var/folders/3f/ts92xp0d3wn31g7_tgj6p_s00000gn/T/pip-install-ec0todpb/apkverify/apkverify/sigverify.py", line 12, in <module>
        from asn1crypto import cms, x509
    ModuleNotFoundError: No module named 'asn1crypto'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3f/ts92xp0d3wn31g7_tgj6p_s00000gn/T/pip-install-ec0todpb/apkverify/
```

**Comment by shuxin** [comment]
maybe something wrong with the config on pipy package.
try
pip install asn1crypto
first

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by krokofant** [comment]
@shuxin I opened a PR to fix this #5

**Comment by shuxin** [comment]
there must be another way.
setup.py must not import the package before it installed.

**Comment by krokofant** [comment]
@shuxin I think you're misreading the changes. What you describe is what used to happen - this change removes that import.

It removes the line https://github.com/shuxin/apk-signature-verify/blob/88d80e1b664a73e7a296739a3564c38dc424d329/apkverify/__init__.py#L5

**Comment by shuxin** [comment]
i known.
that line is for useage of ```from apkverify import ApkSignature``` instead of ```from apkverify.apkverify import ApkSignature``
I means that a better solution is to fix the setup.py

**Comment by krokofant** [comment]
I thought about moving the metadata but it was used in several places. Is that import in `__init__.py` required? I'm not especially familiar with python.

**Comment by shuxin** [comment]
I'm not especially familiar with python too. 😟
I think I should clean the setup.py

**Comment by krokofant** [comment]
I'll provide another PR in a moment

**Comment by krokofant** [comment]
@shuxin I've moved out the metadata in this PR #6

**Comment by shuxin** [comment]
great, many thanks.

**Comment by krokofant** [comment]
@shuxin You're welcome. Thanks for the module. Please do a new release when you have time.
